# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: karma.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils.utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='karma.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bkarma.proto\x1a\x0butils.proto\"4\n\x12ModifyKarmaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x05\"7\n\x13ModifyKarmaResponse\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.OperationStatus\"\x1f\n\x0cKarmaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"@\n\rKarmaResponse\x12\r\n\x05karma\x18\x01 \x01(\x05\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.OperationStatus\"$\n\x13\x41\x64\x64KarmaUserRequest\x12\r\n\x05karma\x18\x01 \x01(\x05\"I\n\x14\x41\x64\x64KarmaUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.OperationStatus\"I\n\x12\x43hooseUsersRequest\x12\x1a\n\x12\x66orbidden_user_ids\x18\x01 \x03(\x05\x12\x17\n\x0fusers_to_choose\x18\x02 \x01(\r\"I\n\x13\x43hooseUsersResponse\x12\x10\n\x08user_ids\x18\x01 \x03(\x05\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.OperationStatus2\xf1\x01\n\x05Karma\x12\x38\n\x0bModifyKarma\x12\x13.ModifyKarmaRequest\x1a\x14.ModifyKarmaResponse\x12)\n\x08GetKarma\x12\r.KarmaRequest\x1a\x0e.KarmaResponse\x12\x36\n\x07\x41\x64\x64User\x12\x14.AddKarmaUserRequest\x1a\x15.AddKarmaUserResponse\x12K\n\x1e\x43hooseKarmaWeightedRandomUsers\x12\x13.ChooseUsersRequest\x1a\x14.ChooseUsersResponseb\x06proto3'
  ,
  dependencies=[utils__pb2.DESCRIPTOR,])




_MODIFYKARMAREQUEST = _descriptor.Descriptor(
  name='ModifyKarmaRequest',
  full_name='ModifyKarmaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ModifyKarmaRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delta', full_name='ModifyKarmaRequest.delta', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=80,
)


_MODIFYKARMARESPONSE = _descriptor.Descriptor(
  name='ModifyKarmaResponse',
  full_name='ModifyKarmaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ModifyKarmaResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=137,
)


_KARMAREQUEST = _descriptor.Descriptor(
  name='KarmaRequest',
  full_name='KarmaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='KarmaRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=170,
)


_KARMARESPONSE = _descriptor.Descriptor(
  name='KarmaResponse',
  full_name='KarmaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='karma', full_name='KarmaResponse.karma', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='KarmaResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=236,
)


_ADDKARMAUSERREQUEST = _descriptor.Descriptor(
  name='AddKarmaUserRequest',
  full_name='AddKarmaUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='karma', full_name='AddKarmaUserRequest.karma', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=274,
)


_ADDKARMAUSERRESPONSE = _descriptor.Descriptor(
  name='AddKarmaUserResponse',
  full_name='AddKarmaUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='AddKarmaUserResponse.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='AddKarmaUserResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=349,
)


_CHOOSEUSERSREQUEST = _descriptor.Descriptor(
  name='ChooseUsersRequest',
  full_name='ChooseUsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='forbidden_user_ids', full_name='ChooseUsersRequest.forbidden_user_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='users_to_choose', full_name='ChooseUsersRequest.users_to_choose', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=424,
)


_CHOOSEUSERSRESPONSE = _descriptor.Descriptor(
  name='ChooseUsersResponse',
  full_name='ChooseUsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='ChooseUsersResponse.user_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='ChooseUsersResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=499,
)

_MODIFYKARMARESPONSE.fields_by_name['status'].enum_type = utils__pb2._OPERATIONSTATUS
_KARMARESPONSE.fields_by_name['status'].enum_type = utils__pb2._OPERATIONSTATUS
_ADDKARMAUSERRESPONSE.fields_by_name['status'].enum_type = utils__pb2._OPERATIONSTATUS
_CHOOSEUSERSRESPONSE.fields_by_name['status'].enum_type = utils__pb2._OPERATIONSTATUS
DESCRIPTOR.message_types_by_name['ModifyKarmaRequest'] = _MODIFYKARMAREQUEST
DESCRIPTOR.message_types_by_name['ModifyKarmaResponse'] = _MODIFYKARMARESPONSE
DESCRIPTOR.message_types_by_name['KarmaRequest'] = _KARMAREQUEST
DESCRIPTOR.message_types_by_name['KarmaResponse'] = _KARMARESPONSE
DESCRIPTOR.message_types_by_name['AddKarmaUserRequest'] = _ADDKARMAUSERREQUEST
DESCRIPTOR.message_types_by_name['AddKarmaUserResponse'] = _ADDKARMAUSERRESPONSE
DESCRIPTOR.message_types_by_name['ChooseUsersRequest'] = _CHOOSEUSERSREQUEST
DESCRIPTOR.message_types_by_name['ChooseUsersResponse'] = _CHOOSEUSERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModifyKarmaRequest = _reflection.GeneratedProtocolMessageType('ModifyKarmaRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYKARMAREQUEST,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:ModifyKarmaRequest)
  })
_sym_db.RegisterMessage(ModifyKarmaRequest)

ModifyKarmaResponse = _reflection.GeneratedProtocolMessageType('ModifyKarmaResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYKARMARESPONSE,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:ModifyKarmaResponse)
  })
_sym_db.RegisterMessage(ModifyKarmaResponse)

KarmaRequest = _reflection.GeneratedProtocolMessageType('KarmaRequest', (_message.Message,), {
  'DESCRIPTOR' : _KARMAREQUEST,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:KarmaRequest)
  })
_sym_db.RegisterMessage(KarmaRequest)

KarmaResponse = _reflection.GeneratedProtocolMessageType('KarmaResponse', (_message.Message,), {
  'DESCRIPTOR' : _KARMARESPONSE,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:KarmaResponse)
  })
_sym_db.RegisterMessage(KarmaResponse)

AddKarmaUserRequest = _reflection.GeneratedProtocolMessageType('AddKarmaUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDKARMAUSERREQUEST,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:AddKarmaUserRequest)
  })
_sym_db.RegisterMessage(AddKarmaUserRequest)

AddKarmaUserResponse = _reflection.GeneratedProtocolMessageType('AddKarmaUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDKARMAUSERRESPONSE,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:AddKarmaUserResponse)
  })
_sym_db.RegisterMessage(AddKarmaUserResponse)

ChooseUsersRequest = _reflection.GeneratedProtocolMessageType('ChooseUsersRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHOOSEUSERSREQUEST,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:ChooseUsersRequest)
  })
_sym_db.RegisterMessage(ChooseUsersRequest)

ChooseUsersResponse = _reflection.GeneratedProtocolMessageType('ChooseUsersResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHOOSEUSERSRESPONSE,
  '__module__' : 'karma_pb2'
  # @@protoc_insertion_point(class_scope:ChooseUsersResponse)
  })
_sym_db.RegisterMessage(ChooseUsersResponse)



_KARMA = _descriptor.ServiceDescriptor(
  name='Karma',
  full_name='Karma',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=502,
  serialized_end=743,
  methods=[
  _descriptor.MethodDescriptor(
    name='ModifyKarma',
    full_name='Karma.ModifyKarma',
    index=0,
    containing_service=None,
    input_type=_MODIFYKARMAREQUEST,
    output_type=_MODIFYKARMARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetKarma',
    full_name='Karma.GetKarma',
    index=1,
    containing_service=None,
    input_type=_KARMAREQUEST,
    output_type=_KARMARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='Karma.AddUser',
    index=2,
    containing_service=None,
    input_type=_ADDKARMAUSERREQUEST,
    output_type=_ADDKARMAUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ChooseKarmaWeightedRandomUsers',
    full_name='Karma.ChooseKarmaWeightedRandomUsers',
    index=3,
    containing_service=None,
    input_type=_CHOOSEUSERSREQUEST,
    output_type=_CHOOSEUSERSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KARMA)

DESCRIPTOR.services_by_name['Karma'] = _KARMA

# @@protoc_insertion_point(module_scope)
