class Constants:
    KEYS_LEN: int = 100
    INITIAL_BALANCE: int = 100
    INITIAL_KARMA: int = 0
    MAX_USERS_LIMIT: int = 100_000
    DATE_FORMAT: str = "%Y-%m-%d"

    MAX_BANK_SERVERS_WORKERS = 2
    MAX_KARMA_SERVERS_WORKERS = 2
    MAX_USERS_SERVERS_WORKERS = 3

    BANK_SERVICE_PORT = 50051
    KARMA_SERVICE_PORT = 50052
    USERS_SERVICE_PORT = 50053
