# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils.utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbank.proto\x1a\x0butils.proto\"M\n\x12TransactionRequest\x12\x14\n\x0c\x66rom_user_id\x18\x01 \x01(\x05\x12\x12\n\nto_user_id\x18\x02 \x01(\x05\x12\r\n\x05\x63oins\x18\x03 \x01(\r\"7\n\x13TransactionResponse\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.OperationStatus\"!\n\x0e\x42\x61lanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"D\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\r\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.OperationStatus\"%\n\x12\x41\x64\x64\x42\x61nkUserRequest\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\r\"H\n\x13\x41\x64\x64\x42\x61nkUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.OperationStatus2\xb0\x01\n\x04\x42\x61nk\x12=\n\x10\x41pplyTransaction\x12\x13.TransactionRequest\x1a\x14.TransactionResponse\x12/\n\nGetBalance\x12\x0f.BalanceRequest\x1a\x10.BalanceResponse\x12\x38\n\x0b\x41\x64\x64\x42\x61nkUser\x12\x13.AddBankUserRequest\x1a\x14.AddBankUserResponseb\x06proto3'
  ,
  dependencies=[utils__pb2.DESCRIPTOR,])




_TRANSACTIONREQUEST = _descriptor.Descriptor(
  name='TransactionRequest',
  full_name='TransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_user_id', full_name='TransactionRequest.from_user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_user_id', full_name='TransactionRequest.to_user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coins', full_name='TransactionRequest.coins', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=104,
)


_TRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='TransactionResponse',
  full_name='TransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TransactionResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=161,
)


_BALANCEREQUEST = _descriptor.Descriptor(
  name='BalanceRequest',
  full_name='BalanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='BalanceRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=196,
)


_BALANCERESPONSE = _descriptor.Descriptor(
  name='BalanceResponse',
  full_name='BalanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='BalanceResponse.balance', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='BalanceResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=266,
)


_ADDBANKUSERREQUEST = _descriptor.Descriptor(
  name='AddBankUserRequest',
  full_name='AddBankUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='AddBankUserRequest.balance', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=305,
)


_ADDBANKUSERRESPONSE = _descriptor.Descriptor(
  name='AddBankUserResponse',
  full_name='AddBankUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='AddBankUserResponse.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='AddBankUserResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=379,
)

_TRANSACTIONRESPONSE.fields_by_name['status'].enum_type = utils__pb2._OPERATIONSTATUS
_BALANCERESPONSE.fields_by_name['status'].enum_type = utils__pb2._OPERATIONSTATUS
_ADDBANKUSERRESPONSE.fields_by_name['status'].enum_type = utils__pb2._OPERATIONSTATUS
DESCRIPTOR.message_types_by_name['TransactionRequest'] = _TRANSACTIONREQUEST
DESCRIPTOR.message_types_by_name['TransactionResponse'] = _TRANSACTIONRESPONSE
DESCRIPTOR.message_types_by_name['BalanceRequest'] = _BALANCEREQUEST
DESCRIPTOR.message_types_by_name['BalanceResponse'] = _BALANCERESPONSE
DESCRIPTOR.message_types_by_name['AddBankUserRequest'] = _ADDBANKUSERREQUEST
DESCRIPTOR.message_types_by_name['AddBankUserResponse'] = _ADDBANKUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionRequest = _reflection.GeneratedProtocolMessageType('TransactionRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:TransactionRequest)
  })
_sym_db.RegisterMessage(TransactionRequest)

TransactionResponse = _reflection.GeneratedProtocolMessageType('TransactionResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONRESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:TransactionResponse)
  })
_sym_db.RegisterMessage(TransactionResponse)

BalanceRequest = _reflection.GeneratedProtocolMessageType('BalanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _BALANCEREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:BalanceRequest)
  })
_sym_db.RegisterMessage(BalanceRequest)

BalanceResponse = _reflection.GeneratedProtocolMessageType('BalanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _BALANCERESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:BalanceResponse)
  })
_sym_db.RegisterMessage(BalanceResponse)

AddBankUserRequest = _reflection.GeneratedProtocolMessageType('AddBankUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDBANKUSERREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:AddBankUserRequest)
  })
_sym_db.RegisterMessage(AddBankUserRequest)

AddBankUserResponse = _reflection.GeneratedProtocolMessageType('AddBankUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDBANKUSERRESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:AddBankUserResponse)
  })
_sym_db.RegisterMessage(AddBankUserResponse)



_BANK = _descriptor.ServiceDescriptor(
  name='Bank',
  full_name='Bank',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=382,
  serialized_end=558,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApplyTransaction',
    full_name='Bank.ApplyTransaction',
    index=0,
    containing_service=None,
    input_type=_TRANSACTIONREQUEST,
    output_type=_TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBalance',
    full_name='Bank.GetBalance',
    index=1,
    containing_service=None,
    input_type=_BALANCEREQUEST,
    output_type=_BALANCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddBankUser',
    full_name='Bank.AddBankUser',
    index=2,
    containing_service=None,
    input_type=_ADDBANKUSERREQUEST,
    output_type=_ADDBANKUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANK)

DESCRIPTOR.services_by_name['Bank'] = _BANK

# @@protoc_insertion_point(module_scope)
