# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bank_pb2 as bank__pb2


class BankStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyTransaction = channel.unary_unary(
                '/Bank/ApplyTransaction',
                request_serializer=bank__pb2.TransactionRequest.SerializeToString,
                response_deserializer=bank__pb2.TransactionResponse.FromString,
                )
        self.GetBalance = channel.unary_unary(
                '/Bank/GetBalance',
                request_serializer=bank__pb2.BalanceRequest.SerializeToString,
                response_deserializer=bank__pb2.BalanceResponse.FromString,
                )
        self.AddUser = channel.unary_unary(
                '/Bank/AddUser',
                request_serializer=bank__pb2.AddUserRequest.SerializeToString,
                response_deserializer=bank__pb2.AddUserResponse.FromString,
                )


class BankServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ApplyTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyTransaction,
                    request_deserializer=bank__pb2.TransactionRequest.FromString,
                    response_serializer=bank__pb2.TransactionResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=bank__pb2.BalanceRequest.FromString,
                    response_serializer=bank__pb2.BalanceResponse.SerializeToString,
            ),
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=bank__pb2.AddUserRequest.FromString,
                    response_serializer=bank__pb2.AddUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bank(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplyTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/ApplyTransaction',
            bank__pb2.TransactionRequest.SerializeToString,
            bank__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/GetBalance',
            bank__pb2.BalanceRequest.SerializeToString,
            bank__pb2.BalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/AddUser',
            bank__pb2.AddUserRequest.SerializeToString,
            bank__pb2.AddUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
